version: '2'
services:
    nginx:
        container_name: nginxlemp
        image: nginx
        ports:
            - "127.0.0.1:80:80"
        links:
            - php
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

            - ./logs/nginx-error.log:/var/log/nginx/error.log
            - ./logs/nginx-access.log:/var/log/nginx/access.log

            - ./public:/code
    php:
        container_name: phpfpmlemp
        image: php:fpm
        ports:
            - "127.0.0.1:9000:9000"
        volumes:
            - ./public:/code
    mysql:
      container_name: marialemp
      image: mariadb
      ports:
          - "127.0.0.1:3306:3306"
      volumes:
          - ./database:/home
      environment:
        MYSQL_ROOT_PASSWORD: pT73HegS6x4s8P3UMWme
        MYSQL_USER: lempadmon
        MYSQL_DATABASE: lemp_db
        MYSQL_PASSWORD: 123123
